apiVersion: v1
kind: Service
metadata:
  name: tb2-ai-service
  namespace: tb2ai
spec:
  type: NodePort
  selector:
    app: tb2-ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # This makes it accessible at http://<minikube-server-ip>:30080
